name: Autograding Tests
on:
  push:
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup bun
      uses: oven-sh/setup-bun@v2
    - name: Tests
      id: tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Tests
        setup-command: ''
        command: bun test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS_RESULTS: "${{steps.tests.outputs.result}}"
      with:
        runners: tests
